# Generated by Django 6.0.3 on 2026-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expedido',
            field=models.CharField(blank=True, choices=[('LP', 'La Paz'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('CB', 'Cochabamba'), ('SC', 'Santa Cruz'), ('BN', 'Beni'), ('PA', 'Pando'), ('TJ', 'Tarija'), ('CH', 'Chuquisaca')], max_length=2, null=True),
        ),
    ]
