# Generated by Django 6.0.3 on 2026-03-14 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('rude', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.gestion')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.paralelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.inscripcion')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.requisito')),
            ],
        ),
    ]
